/*Здесь в базу добавляются процедурыы*/


SET TERM ^ ;
CREATE OR ALTER PROCEDURE GET_SLOVAR_PEOPLES
RETURNS (
    NAME_TIP VARCHAR(255),
    ID integer,
    FAM FIO,
    NAM FIO,
    OTCH FIO,
	place_education VARCHAR(255),
	PHONE_HOME VARCHAR(20) CHARACTER SET WIN1251  COLLATE PXW_CYRL,
	PHONE_WORK VARCHAR(20) CHARACTER SET WIN1251  COLLATE PXW_CYRL,
	PHONE_SOTE VARCHAR(20) CHARACTER SET WIN1251  COLLATE PXW_CYRL,
    DTB DATE,
    VOZR integer,
    PLB VARCHAR(255),
    REGISTRATION VARCHAR(255),
	PASPORT VARCHAR(255) CHARACTER SET WIN1251   COLLATE PXW_CYRL,
	SNILS VARCHAR(11) CHARACTER SET WIN1251   COLLATE PXW_CYRL,
	INN VARCHAR(12) CHARACTER SET WIN1251   COLLATE PXW_CYRL,
    LASTWORK integer,
    CHILDRENS INTEGER)
AS
BEGIN

for select TIP_EDUCATION.NAME as NAME_TIP, PEOPLES.ID as ID, PEOPLES.FAM as FAM, PEOPLES.NAM, PEOPLES.OTCH, PEOPLES.place_education, PEOPLES.phone_home as PHONE_HOME,
PEOPLES.phone_work as PHONE_work, PEOPLES.phone_SOTE as PHONE_SOTE,
PEOPLES.DTB as DTB, datediff(year from cast (PEOPLES.DTB as date) to current_date) AS VOZR, PEOPLES.PLB as PLB, PEOPLES.REGISTRATION as REGISTRATION,
PEOPLES.PASPORT, PEOPLES.SNILS, PEOPLES.INN,
count(WORKS.ID), count(CHILDRENS.ID) as LASTWORK
from  PEOPLES left join WORKS on (PEOPLES.ID=WORKS.ID_PEOPLES) left join CHILDRENS ON (CHILDRENS.ID_PEOPLE=PEOPLES.ID)
left join TIP_EDUCATION ON (PEOPLES.ID_TIP_EDUCATION=TIP_EDUCATION.ID)
group by NAME_TIP, PEOPLES.ID, PEOPLES.FAM, PEOPLES.NAM, PEOPLES.OTCH, PEOPLES.place_education, PHONE_HOME, PHONE_WORK, PHONE_SOTE,  PEOPLES.DTB, VOZR, PEOPLES.PLB, PEOPLES.PASPORT, PEOPLES.SNILS, PEOPLES.INN,
PEOPLES.REGISTRATION order by PEOPLES.fam, PEOPLES.nam, PEOPLES.otch
into :NAME_TIP, :ID, :FAM, :NAM, :OTCH, :place_education, :PHONE_HOME, :PHONE_WORK, :PHONE_SOTE, :DTB, :VOZR, :PLB, :REGISTRATION, :PASPORT, :SNILS, :INN,
:LASTWORK, :CHILDRENS
DO SUSPEND;
END^
SET TERM ; ^

commit;







/*Процедура создает роли*/
SET TERM ^ ;
CREATE PROCEDURE CreateRole
AS
DECLARE VARIABLE STMP VARCHAR(255);
BEGIN
/*создаем роль admiunistrator*/
STMP='CREATE ROLE administrator;';
EXECUTE STATEMENT STMP;
STMP='CREATE ROLE statist;';
EXECUTE STATEMENT STMP;
STMP='CREATE ROLE kadri;';
EXECUTE STATEMENT STMP;
STMP='CREATE ROLE boss;';
EXECUTE STATEMENT STMP;
/*назначаем роли привелегии на таблицы*/
STMP='GRANT select ON USERS TO PUBLIC;';
EXECUTE STATEMENT STMP;
STMP='GRANT select ON RAIONS TO PUBLIC;';
EXECUTE STATEMENT STMP;
STMP='GRANT select ON SEX TO PUBLIC;';
EXECUTE STATEMENT STMP;
STMP='GRANT select ON PR_RASPR_MNI TO PUBLIC;';
EXECUTE STATEMENT STMP;
STMP='GRANT select ON KEY_ TO PUBLIC;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON PEOPLES TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON USERS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON RAIONS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON LOCATIONS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON WORKS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON POSTS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON GROUPS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MOTIVE_DISCHARGE TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON START_WORK TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON COND_START_WORK TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON DOP TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON SVIAZ_SW_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON DISCHARGE TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MOVE_EMPL TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON TMP_STOP_SW TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MOTIVE_TMP_STOP_SW TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MNI TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MNI_MODEL TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON MNI_TIP TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  MOTIVE_DELETE_MNI TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  DELETE_MNI TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  MOVE_MNI TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SVIAZ_MNI_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  CHILDRENS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SERTIFIKATS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SVIAZ_SERT_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  KRIPTO TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  COPY_KRIPTO TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  DELETE_KRIPTO TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SVIAZ_COPY_KRIPTO_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  MOTIVE_DEL_KRIPTO TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  DELETE_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TMP_STOP_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SVIAZ_SB_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TIP_EDUCATION TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  DELETE_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TMP_STOP_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  SVIAZ_SB_DOCS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  COLORS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TIP_MEMORY TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TIP_PROC TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  NAME_OS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  NAME_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  PR_RASPR_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  STIKER_SB TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TIP_LICENSE_OS TO administrator;';
EXECUTE STATEMENT STMP;
STMP='GRANT ALL ON  TIP_WORK_SB TO administrator;';
EXECUTE STATEMENT STMP;
/*назначаем роли привелегии на процедуры*/
STMP='GRANT EXECUTE ON PROCEDURE GET_SLOVAR_PEOPLES TO administrator;';
EXECUTE STATEMENT STMP;
/*назначаем роли пользователям*/
STMP='GRANT administrator TO u03408001;';
EXECUTE STATEMENT STMP;
END^
SET TERM ; ^







