/*Здесь в базу добавляются процедурыы*/
/*Процедура выводит все MNI*/
SET TERM ^ ;
CREATE PROCEDURE ALL_MNI 
RETURNS (
  ID INTEGER,
      UCHETN_NOM VARCHAR(10),
  SERIAL VARCHAR(100),
  mni_KEY TRUE_FALSE,
  mni_SIZE INTEGER,
  DTP DATE,
  DTS DATE,
  OBOSNOVANIE VARCHAR(255),
  OTKUDA VARCHAR(255),
  DOPOLN VARCHAR(255),
  MODEL_NAME VARCHAR(50),
  TIP_NAME VARCHAR(50),
  FAM FIO,
  NAM FIO,
  OTCH FIO,
  DOLJN VARCHAR(150),
  uGROUP VARCHAR(30),
  SB_SERIAL VARCHAR(50),
  SB_INVENT VARCHAR(15),
  PLACE VARCHAR(100)
     )
AS
BEGIN
for select MNI.ID, mni.UCHETN_NOM, MNI.SERIAL, MNI.MNI_KEY, MNI.MNI_SIZE, MNI.DTP, MNI.DTS, MNI.OBOSNOVANIE, MNI.OTKUDA, MNI.DOPOLN, 
mni_model.name as model, mni_tip.name as tip, users.fam, users.nam,users.otch, USERS_DOLJN.NAME AS DOLJN, USERS_GROUP.NAME AS uGROUP,
SB.SERIAL AS SB_SERIAL, SB.INVENT AS SB_INVENT, PLACE.NAME AS PLACE  from mni join mni_model on mni.id_model=mni_model.id join mni_tip on mni_tip.id=mni.id_tip
join users on mni.id_user=users.id LEFT join sb on sb.id=mni.id_sb LEFT join place on sb.id_place=place.id
LEFT JOIN USERS_DOLJN ON
USERS_DOLJN.ID=USERS.ID_DOLJN LEFT JOIN USERS_GROUP ON USERS_GROUP.ID=USERS.ID_GROUP  
into :ID, :UCHETN_NOM, :SERIAL, :mni_KEY, :mni_SIZE, :DTP, :DTS, :OBOSNOVANIE, :OTKUDA, :DOPOLN, :MODEL_NAME, :TIP_NAME, :FAM, :NAM, :OTCH,
:DOLJN, :uGROUP, :SB_SERIAL, :SB_INVENT, :PLACE
DO SUSPEND;
END^
SET TERM ; ^


/*Процедура выводит все SB*/
SET TERM ^ ;
CREATE PROCEDURE ALL_SB 
RETURNS (
  ID INTEGER,
      INVENT VARCHAR(15),
  SERIAL VARCHAR(50),
  STIKER VARCHAR(6),  
  DTP DATE,
  DTI DATE,
  DTS DATE,
  OBOSNOVANIE VARCHAR(255),
  LICENSE VARCHAR(50),
  GARANTIA SMALLINT,
  MODEL VARCHAR(50),
  COLOR varchar(30),
  COUNT_IADRA SMALLINT,
  SPEED SMALLINT,   
  PROCNAME VARCHAR(100),  
  MEMORY VARCHAR(100),
  MEMSIZE SMALLINT,
  MEMSPEED SMALLINT,
  UFAM FIO,
  UNAM FIO,
  UOTCH FIO,
  DOLJN VARCHAR(150),
  UGROUP VARCHAR(30),
  PLACE VARCHAR(100),
  DOPOLN VARCHAR(255)
     )
AS
BEGIN
for select SB.ID, SB.INVENT, SB.SERIAL, SB_STIKER.NAME AS SBSTIKER, SB.DTP, SB.DTI, SB.DTS, SB.OBOSNOVANIE, SB.LICENSE, SB.GARANTIA, 
SB_MODEL.NAME AS SBMODEL, COLOR.NAME AS COLOR, SB.PROC_COUNT_IADRA, SB.PROC_SPEED, PROC_TYP.NAME AS SBPROC, MEMORY_TIP.NAME AS MEMTIP,
SB.MEMORY AS MEMSIZE, SB.MEMORY_SPEED, USERS.FAM, USERS.NAM, USERS.OTCH, USERS_DOLJN.NAME AS DOLJN, USERS_GROUP.NAME AS UGROUP, PLACE.NAME AS PLACE, SB.DOPOLN from SB JOIN SB_MODEL ON SB.ID_MODEL=SB_MODEL.ID JOIN COLOR ON
SB.ID_COLOR=COLOR.id JOIN PROC_TYP ON SB.ID_PROC=PROC_TYP.ID JOIN PLACE ON SB.ID_PLACE=PLACE.ID JOIN USERS ON SB.ID_USER=USERS.ID JOIN MEMORY_TIP ON
SB.ID_MEMORY=MEMORY_TIP.ID LEFT JOIN SB_STIKER ON SB.ID_STIKER=SB_STIKER.ID JOIN USERS_DOLJN ON USERS.ID_DOLJN=USERS_DOLJN.ID 
JOIN USERS_GROUP ON USERS.ID_GROUP=USERS_GROUP.ID
into :ID, :INVENT, :SERIAL, :STIKER, :DTP, :DTI, :DTS, :OBOSNOVANIE, :LICENSE, :GARANTIA, :MODEL, :COLOR, :COUNT_IADRA, :SPEED, :PROCNAME,
:MEMORY, :MEMSIZE, :MEMSPEED, :UFAM, :UNAM, :UOTCH, :DOLJN, :uGROUP, :PLACE, :DOPOLN
DO SUSPEND;
END^
SET TERM ; ^

/*Процедура выводит все RAZNOE*/
SET TERM ^ ;
CREATE PROCEDURE ALL_RAZNOE 
RETURNS (
  ID INTEGER,
  SERIAL VARCHAR(100),
  INVENT VARCHAR(15), 
  DTS DATE,
  OBOSNOVANIE VARCHAR(255),
  OPISANIE VARCHAR(500),  
  MODEL VARCHAR(50),
  NAM VARCHAR(50),  
  UFAM FIO,
  UNAM FIO,
  UOTCH FIO,
  DOLJN VARCHAR(150),
  UGROUP VARCHAR(30),
  PLACE VARCHAR(100),
  DOPOLN VARCHAR(255)
     )
AS
BEGIN
for select RAZNOE.ID, RAZNOE.SERIAL, RAZNOE.INVENT, RAZNOE.DTS, RAZNOE.OBOSNOVANIE, RAZNOE.OPISANIE, RAZNOE_MODEL.NAME AS MODEL,
RAZNOE_NAME.NAME AS RNAME, USERS.FAM, USERS.NAM, USERS.OTCH, USERS_DOLJN.NAME AS DOLJN, USERS_GROUP.NAME AS uGROUP, PLACE.NAME AS PLACE, RAZNOE.DOPOLN from RAZNOE JOIN RAZNOE_MODEL ON RAZNOE.ID_MODEL=RAZNOE_MODEL.ID JOIN RAZNOE_NAME ON RAZNOE.ID_NAME=RAZNOE_NAME.ID JOIN PLACE ON RAZNOE.ID_PLACE=PLACE.ID JOIN USERS ON RAZNOE.ID_USER=USERS.ID JOIN USERS_DOLJN ON USERS.ID_DOLJN=USERS_DOLJN.ID JOIN USERS_GROUP ON USERS.ID_GROUP=USERS_GROUP.ID
into :ID, :SERIAL, :INVENT, :DTS, :OBOSNOVANIE, :OPISANIE, :MODEL, :NAM, :UFAM, :UNAM, :UOTCH, :DOLJN, :uGROUP, :PLACE, :DOPOLN
DO SUSPEND;
END^
SET TERM ; ^

/*Процедура выводит всеX USERS*/
SET TERM ^ ;
CREATE PROCEDURE ALL_USERS 
RETURNS (
  	ID INTEGER,
	TAB_NOM VARCHAR(4),
	FAM FIO,
	NAM FIO,
	OTCH FIO,
	DTB DATE,
	DTP DATE,
	DTU DATE,
	SEX SEX_USER,
	PLB VARCHAR(255),
	DOLJN VARCHAR(150),
	UGROUP VARCHAR(30),
	PLACE VARCHAR(100),
	DOPOLN VARCHAR(255)  
     )
AS
BEGIN
for select USERS.ID, USERS.TAB_NOM, USERS.FAM, USERS.NAM, USERS.OTCH, USERS.DTB, USERS.DTP, USERS.DTU, USERS.SEX, USERS.PLB, USERS_DOLJN.NAME AS DOLJN,
USERS_GROUP.NAME AS UGROUP, PLACE.NAME AS PLACE, USERS.DOPOLN from USERS JOIN USERS_DOLJN ON USERS.ID_DOLJN=USERS_DOLJN.ID 
JOIN USERS_GROUP ON USERS.ID_GROUP=USERS_GROUP.ID JOIN PLACE ON USERS.ID_PLACE=PLACE.ID
into :ID, :TAB_NOM, :FAM, :NAM, :OTCH, :DTB, :DTP, :DTU, :SEX, :PLB, :DOLJN, :uGROUP, :PLACE, :DOPOLN
DO SUSPEND;
END^
SET TERM ; ^


